#Se for trabalhar com kubernets tem que ser no padrão yml
#ESSA E A CONFIG DEFAULT
spring:
  application:
    name: greeting-service
#Spring Actuator mostra confiurações sobre o projeto: total de endpoits, se esta rodando ou não, etc... nesse caso ira mostras o maximo de informação
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greeting-service:
  greeting: "hello"
  default-value: "word"


